# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # Use the same key for each machine
    # config.ssh.insert_key = false

    # Every Vagrant virtual environment requires a box to build off of.
    config.vm.box = "ubuntu/xenial64"

    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    config.vm.network "private_network", ip: "192.168.33.10"

    # If true, then any SSH connections made will enable agent forwarding.
    config.ssh.forward_agent = true

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 2
    end

    config.vm.provision "shell", inline: <<-SHELL
      sudo apt-get install -y python-simplejson
    SHELL
end
