---
- name: set nginx site config files
  template: src=host.conf.j2 dest=/etc/nginx/vhosts/{{ item.name }}.conf
  with_items: domains
  notify: restart nginx
  sudo: True
- name: touch custom nginx site config
  file: path=/etc/nginx/vhosts/{{ item.name }}.custom state=touch
  with_items: domains
  changed_when: false
  sudo: True
- name: create domain groups
  group: name={{ item.user }}
  with_items: domains
  sudo: True
- name: create domain users
  user: name={{ item.user }} group={{ item.user }} password={{ item.pass }}
  with_items: domains
  sudo: True
- name: create logs dir
  file: path={{ item.home }}/logs/ owner={{ item.user }} group={{ item.user }} state=directory
  with_items: domains
  sudo: True
- name: touch error.log
  file: path={{ item.home }}/logs/{{ item.name }}.error.log owner={{ item.user }} group={{ item.user }} state=touch
  with_items: domains
  changed_when: false
  sudo: True
  notify: restart nginx
- name: create app dir
  file: path={{ item.path }} owner={{ item.user }} group={{ item.user }} recurse=yes state=directory
  with_items: domains
  sudo: True
- name: Create a dummy index file for nginx too
  template: src=index.php.j2 dest={{ item.path }}/index.php owner={{ item.user }} group={{ item.user }} 
  with_items: domains
  sudo: True
