---
- name: set host configs
  template: src=www.conf.j2 dest={{ php_fpm_dir }}/pool.d/{{ item.name }}.conf
  with_items: domains
  sudo: True
  notify: restart php5
- name: create domain groups
  group: name={{ item.user }}
  with_items: domains
  sudo: True
- name: create domain users
  user: name={{ item.user }} group={{ item.user }} password={{ item.pass }}
  with_items: domains
  sudo: True
- name: create app dir
  file: path={{ item.path }} owner={{ item.user }} group={{ item.user }} recurse=yes state=directory
  with_items: domains
  sudo: True
- name: create logs dir
  file: path={{ item.home }}/logs/ owner={{ item.user }} group={{ item.user }} state=directory
  with_items: domains
  sudo: True
- name: touch error.log
  file: path={{ item.home }}/logs/php_error.log owner={{ item.user }} group={{ item.user }} state=touch
  with_items: domains
  changed_when: false
  sudo: True
  notify: restart php5
- name: Create a dummy index file
  template: src=index.php.j2 dest={{ item.path }}/index.php owner={{ item.user }} group={{ item.user }} 
  with_items: domains
  sudo: True
