---
#- name: deploy mariadb
#  hosts: db
#  roles:
#    - db

- name: deploy php
  hosts: web
  roles:
  #    - common
    - phpfpm

- name: deploy nginx
  hosts: nginx
  roles:
  #    - common
    - nginx
