---
- name: install mariadb repository
  apt_repository: repo='deb http://ftp.igh.cnrs.fr/pub/mariadb/repo/10.1/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} main' state=present
  become: true
- name: add repository key
  apt_key: keyserver=keyserver.ubuntu.com id=0xcbcb082a1bb943db
  become: true
- name: install mariadb
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600 allow_unauthenticated=yes
  with_items:
    - mariadb-server
    - python-mysqldb
  become: true
- name: set conf file
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf
  become: true
- name: restart db
  service: name=mysql state=restarted
  become: true
- name: create domain related databases
  mysql_db: name={{ item.db }} state=present
  with_items: "{{ domains }}"
  become: true
- name: create domain related users
  mysql_user: host="%" name={{ item.user }} password={{ item.pass }} priv={{ item.db }}.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP state=present
  with_items: "{{ domains }}"
  become: true
