---
- name: ensure nginx to apt-key
  apt_key: url=http://nginx.org/keys/nginx_signing.key
  become: true

- name: ensure nginx apt repository
  apt_repository: repo="deb http://nginx.org/packages/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} nginx"
  become: true

- name: install nginx
  apt: pkg=nginx update_cache=yes cache_valid_time=3600
  become: true

- name: set nginx config file
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: restart nginx
  become: true

- name: assure ssl directory exists
  file: path=/etc/nginx/{{ item }} state=directory
  become: true
  with_items:
    - ssl
    - sites-available
    - sites-enabled

- name: set nginx site config files
  template: src=host.conf.j2 dest=/etc/nginx/sites-available/{{ item.name }}.conf
  with_items: "{{ domains }}"
  notify: restart nginx
  become: true

- name: link nginx site config to sites-enabled
  file: src=/etc/nginx/sites-available/{{ item.name }}.conf dest=/etc/nginx/sites-enabled/{{ item.name }}.conf state=link
  with_items: "{{ domains }}"
  notify: restart nginx
  become: true

- name: create logs dir
  file: path={{ item.home }}/logs/ owner={{ item.user }} group={{ item.user }} state=directory
  with_items: "{{ domains }}"
  notify: restart nginx

- name: touch error.log
  file: path={{ item.home }}/logs/{{ item.name }}.error.log owner={{ item.user }} group={{ item.user }} state=touch
  with_items: "{{ domains }}"
  become: true
  notify: restart nginx
